// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// DEPRECATED: This module is no longer supported
///
/// All QUIC terminal functionality has been migrated to the new message-based architecture.
/// Please use the functions in message_bridge.rs instead.
Future<String> legacyQuicDeprecatedNotice() =>
    RustLib.instance.api.crateQuicBridgeLegacyQuicDeprecatedNotice();
