// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterMessageClient>>
abstract class FlutterMessageClient implements RustOpaqueInterface {
  static Future<FlutterMessageClient> default_() =>
      RustLib.instance.api.crateMessageBridgeFlutterMessageClientDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<FlutterMessageClient> newInstance() =>
      RustLib.instance.api.crateMessageBridgeFlutterMessageClientNew();
}

/// Flutter远程终端信息
class FlutterRemoteTerminal {
  final String id;
  final String? name;
  final String shellType;
  final String currentDir;
  final (int, int) size;
  final bool running;
  final BigInt createdAt;

  const FlutterRemoteTerminal({
    required this.id,
    this.name,
    required this.shellType,
    required this.currentDir,
    required this.size,
    required this.running,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      shellType.hashCode ^
      currentDir.hashCode ^
      size.hashCode ^
      running.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterRemoteTerminal &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          shellType == other.shellType &&
          currentDir == other.currentDir &&
          size == other.size &&
          running == other.running &&
          createdAt == other.createdAt;
}

/// Flutter系统状态信息
class FlutterSystemStatus {
  final String status;
  final BigInt uptime;
  final int activeTerminals;
  final int activeTcpSessions;
  final BigInt memoryUsage;

  const FlutterSystemStatus({
    required this.status,
    required this.uptime,
    required this.activeTerminals,
    required this.activeTcpSessions,
    required this.memoryUsage,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      uptime.hashCode ^
      activeTerminals.hashCode ^
      activeTcpSessions.hashCode ^
      memoryUsage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSystemStatus &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          uptime == other.uptime &&
          activeTerminals == other.activeTerminals &&
          activeTcpSessions == other.activeTcpSessions &&
          memoryUsage == other.memoryUsage;
}

/// Flutter TCP转发会话信息
class FlutterTcpForwardingSession {
  final String id;
  final String localAddr;
  final String remoteEndpoint;
  final String forwardingType;
  final int activeConnections;
  final BigInt bytesSent;
  final BigInt bytesReceived;
  final BigInt createdAt;

  const FlutterTcpForwardingSession({
    required this.id,
    required this.localAddr,
    required this.remoteEndpoint,
    required this.forwardingType,
    required this.activeConnections,
    required this.bytesSent,
    required this.bytesReceived,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      localAddr.hashCode ^
      remoteEndpoint.hashCode ^
      forwardingType.hashCode ^
      activeConnections.hashCode ^
      bytesSent.hashCode ^
      bytesReceived.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterTcpForwardingSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          localAddr == other.localAddr &&
          remoteEndpoint == other.remoteEndpoint &&
          forwardingType == other.forwardingType &&
          activeConnections == other.activeConnections &&
          bytesSent == other.bytesSent &&
          bytesReceived == other.bytesReceived &&
          createdAt == other.createdAt;
}
